class Tags {
  static List<String> ListPfTags() => [
        "Seafood",
        "Healthy",
        "Italian",
        "Mexican",
        "Soup",
        "Sandwich",
        "Fast Food",
        "American",
        "Appetizer",
        "Salad",
        "Spicy",
        "Breakfast",
        "Comfort Food",
        "Meat",
        "Asian",
        "BBQ",
        "Mediterranean",
        "Vegetarian",
        "French",
        "Russian",
        "International",
        "Indian",
        "Thai",
        "Middle" "Eastern",
        "Wrap",
      ];
}
